var GlobalOptions = {
	btWatchdog: true,
	btNoMoreRy: false,
	btWideScreenStyle: 'normal',
	btPowerBar: false,
	btFloatingPowerBar: true,
	btPowerBarPopups: true,
	btPowerBarOpen: false,
	DashboardToggle: true,
	btOverviewDashboardBtn: true,
	btChatOnRight: false,
	btChatBeforeDash: true,
	btWideMap: true,
	btWinSize: { x: 1000, y: 100 },
	btTrackOpen: true,
	btTransparent: false,
	btKocBgColor: '#ffffff', // Color de fondo del contenedor del juego (#kocContainer)
	AutoUpdates: true,
	UpdateLocation: 1, // 0 - SourceForge, 1 - Greasyfork, 2 - GitHub
	ExtendedDebugMode: false,
	InOutToggle: true,
	MarchPlusToggle: true,
	BattleToggle: true,
	TokenEnabled: true,
	LastTopURL: '',
	GlobalOptionsVersion: '0',
	ExtraTabsVersion: '0',
	TabAutoCheck: true,
	ExtraTabs: [
		{ "source": EXTERNAL_RESOURCE + "tabs/AutoDF.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/BulkAttack.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Defend.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Raid.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/GuardWidget.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Debug.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Tournament.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Megalith.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Aport.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Throne.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Champ.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Research.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Boss.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Resources.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/MAR.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
		{ "source": EXTERNAL_RESOURCE + "tabs/Joust.js", "data": null, "enabled": false, "lastchecked": 0, "version": "" },
	],
};
