var UserOptions = {
	autoPublishGamePopups: false,
	autoCancelGamePopups: true,
	autoPublishPrivacySetting: 40,
	CustomPublish: {},
	CustomListId: "",
	TokenAuto: false,
	OverrideRefresh: "",
	TokenDomain: null,
	TokenDate: 0,
	TokenCount: 0,
	TokenLink: "",
	TokenCollected: false,
	LastTokenStatus: "",
	BuildLink: "",
	BuildCollected: false,
	LastBuildStatus: "",
	ChestDomainList: "",
	ChestCollected: {},
	BadChestDomains: {},
	BonusCollected: false,
	LastChestStatus: "",
	TreasureChest: true,
	BankTreasureChests: true,
	MaxBankedTreasureChests: 500,
	TreasureChestBank: [], // {tokenId, feedId, serverId, playerId, tileName, unixTime_taken, link}
	TreasureChestBankOther: [],
	TokenRequest: "",
	TokenResponse: "",
	TokenSuccessLink: "",
	TokenChestFeedId: 0,
	TokenChestUID: 0,
};
